WebGentle.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebGentle.BookStore.Repository;

namespace WebGentle.BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

WebGentle.BookStore/Views/Book/GetAllBooks.cshtml
@{
    ViewData["Title"] = "All books";
}

@model IEnumerable<BookModel>

<div class="container">
    <h3 class="display-4">All books</h3>
    <div class="row">

        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <partial name="_bookThumbnail" model="@book" />
            </div>
        }
    </div>
</div>

WebGentle.BookStore/Views/Book/GetBook.cshtml
@{
    ViewData["Title"] = "Book detail " + Model.Title;
}

@model BookModel

<div class="container">
    <h3 class="display-4">Book details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
                <div class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" class="@(i==0 ? "active" : "")" aria-current="true" aria-label="Slide 1"></button>
                    }
                </div>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class="@(i==0 ? "carousel-item active" : "carousel-item")">
                            <img class="d-block w-100" asp-append-version="true" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                        </div>
                    }
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>

        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Read Now
                    </a>
                </div>
            </div>

            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span>@Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total pages - </span>@Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span>@Model.Language</li>
            </ul>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg  h-100">
            <div class="modal-content  h-100">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <embed src="@Model.BookPdfUrl" class="w-100 h-100" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <hr />

    <div class="py-5 bg-light">
        <div class="container">
            <h3 class="h3">Similar books</h3>
            <div class="row">
                <vc:top-books count="6"></vc:top-books>
            </div>
        </div>
    </div>
</div>